# This is a basic workflow to help you get started with Actions

name: 카카오북 App Staging Debug

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 소스 체크아웃
        uses: actions/checkout@v2
      
      - name: JDK 1.8 설정
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 성공적으로 빌드가 될까요?
          echo Good Luck!
          
      - name: gradlew permission change
        run: chmod +x ./gradlew
          
      - name: Build with Gradle
        run: sudo ./gradlew clean assembleDebug
      
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug
